image: Visual Studio 2022

build:
  verbosity: detailed

artifacts:
  - path: /src/**/*.nupkg

build_script:
  - cmd: dotnet restore src/Felicity --locked-mode
  - cmd: dotnet restore
  - cmd: dotnet build -c Release --no-restore

test_script:
  - cmd: dotnet test -c Release --no-build -- Expecto.fail-on-focused-tests=true

deploy:
  - provider: NuGet
    api_key:
      secure: UfD+4sQlK11i2QfzXP2v3QeFIKY4Vqmu+IaMkPqYDwcXLY+zrow2A+gc6Mve14iI
    on:
      appveyor_repo_tag: true
