image: Visual Studio 2022

build:
  verbosity: detailed

artifacts:
  - path: /src/**/*.nupkg

build_script:
  - cmd: dotnet restore --locked-mode
  - cmd: dotnet build -c Release

test_script:
  - cmd: dotnet test -c Release --no-build -- Expecto.fail-on-focused-tests=true

deploy:
  - provider: NuGet
    api_key:
      secure: ShCozsRJDtIugmkNgMhsTBA+xT8KwA74lxgXrylqNArS0P5wxGE2FAZJPF2jPBNN
    on:
      appveyor_repo_tag: true
