image: Visual Studio 2019

build:
  verbosity: detailed

artifacts:
  - path: /src/**/*.nupkg

build_script:
  - cmd: dotnet build -c Release

test_script:
  - cmd: dotnet test -c Release --no-build

deploy:
  - provider: NuGet
    api_key:
      secure: ShCozsRJDtIugmkNgMhsTBA+xT8KwA74lxgXrylqNArS0P5wxGE2FAZJPF2jPBNN
    on:
      appveyor_repo_tag: true
